# Generated by Django 5.0.7 on 2024-11-11 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='command',
            old_name='broadcaster_id',
            new_name='broadcaster',
        ),
        migrations.RenameField(
            model_name='variable',
            old_name='broadcaster_id',
            new_name='broadcaster',
        ),
        migrations.RemoveField(
            model_name='command',
            name='command_id',
        ),
    ]
