# Generated by Django 5.0.7 on 2024-11-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_rename_broadcaster_id_command_broadcaster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_mod',
            field=models.BooleanField(default=False),
        ),
    ]
