# Generated by Django 5.0.7 on 2024-11-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0003_alter_command_command_mod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_function',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_time',
            field=models.IntegerField(blank=True),
        ),
    ]
