# Generated by Django 5.0.7 on 2024-12-17 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0004_alter_command_command_function_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='variable',
            name='variable_value',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='command',
            name='command_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ListVariableItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_value', models.CharField(max_length=500)),
                ('broadcaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variable_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commands.variable')),
            ],
        ),
    ]
