# Generated by Django 5.0.7 on 2025-01-09 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0005_variable_variable_value_alter_command_command_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='command_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='variable',
            name='variable_name',
            field=models.CharField(max_length=50),
        ),
    ]
