# Generated by Django 5.0.7 on 2024-11-11 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='bot_active',
            field=models.BooleanField(default=0),
        ),
    ]
